Upated create-links to use getopt, and minor update to manual to reflect changes.

diff --git a/scripts/create-links b/scripts/create-links
--- a/scripts/create-links
+++ b/scripts/create-links
@@ -1,9 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 # $Id$
 #----------------------------------------------------------------------------
 
-usage()
-{
+PATH=.:/bin:/usr/bin
+
+usage(){
 cat <<EOF
 
 create-links
@@ -11,98 +12,92 @@ create-links
 
 DESCRIPTION:
 
-  This short script creates symlinks for files named prefixn.suffix to files
-named prefixm.suffix which may or may not be in the current directory.  n is
-any index which differentiates the files.  m is another index with a fixed
-number of digits incremented by 1 for each file.
+Create symbolic links for files named prefixn.suffix to files named
+prefixm.suffix which may or may not be in the current directory.  n is any
+index which differentiates the files.  m is another index with a fixed number
+of digits incremented by 1 for each file.
 
 USAGE:
 
-        create-links [OPTIONS]
-          Use with no options to create the links with the default options
+        create-links [OPTIONS] <linkdir>
 
 OPTIONS:
 
-        --symlinks=
-                    links directory [links]
-        --procdir=
+        -d <process directory>|--procdir=<process directory>
                     process directory prefix [proc]
-        --prefix=
-                    filename prefix [dens]
-        --suffix=
-                    filename suffix [dat]
-        --num_zeros=
-                    number of zeros in the filename [7]
-        --start=
-                    which index to start the links at [0]
-        --help
+
+        -h|--help
                     display this help
+
+        -i <index>|--startindex=<index>
+                    which index to start the links at [0]
+
+        -l <link directory>|--linkdir=<link directory>
+                    links directory [links]
+
+        -n <num zeros>|--numzeros=<num zeros>
+                    number of zeros in the filename [7]
+
+        -p <prefix>|--prefix=<prefix>
+                    filename prefix [dens]
+
+        -s <suffix>|--suffix=<suffix>
+                    filename suffix [dat]
 
 EOF
 }
 
-while [ $# -gt 0 ]
+# Get command line options
+options=`getopt -o d:hi:n:p:s: -l procdir:,help,startindex:,numzeros:,prefix:,suffix: -n create-links -- "$@"`
+
+# If no options, show the help
+if [ $# == 0 ]; then
+  usage
+  exit 1
+fi
+
+eval set -- "$options"
+
+procdir='proc'
+start=0
+numzeros=7
+prefix='dens'
+suffix='dat'
+
+# Set parameters depending on options
+while true
 do
-  case $1 in
-    --symlinks=*)
-      symlinks=`echo $1 | sed s/--"symlinks="//`
-    ;;
-    --procdir=*)
-      procdir=`echo $1 | sed s/--"procdir="//`
-    ;;
-    --prefix=*)
-      prefix=`echo $1 | sed s/--"prefix="//`
-    ;;
-    --suffix=*)
-      suffix=`echo $1 | sed s/--"suffix="//`
-    ;;
-    --num_zeros=*)
-      num_zeros=`echo $1 | sed s/--"num_zeros="//`
-    ;;
-    --start=*)
-      start=`echo $1 | sed s/--"start="//`
-    ;;
-    -h)
-      usage; exit 1
-    ;;
-    -?)
-      usage; exit 1
-    ;;
-    --help)
-      usage; exit 1
-    ;;
-    *)
-      echo UNRECOGNISED PARAMETER
-      usage; exit 1
-    ;;
+  case "$1" in
+    -d|--procdir) procdir=$2; shift 2;;
+    -i|--startindex) start=$2; shift 2;;
+    -n|--numzeros) numzeros=$2; shift 2;;
+    -p|--prefix) prefix=$2; shift 2;;
+    -s|--suffix) suffix=$2; shift 2;;
+    -h|--help) usage; exit 1;;
+    --) shift ; break ;;
+    *) echo "Invalid flag" ; exit 1 ;;
   esac
-  shift
 done
 
-[ "$symlinks" ] || symlinks='links'
-[ "$procdir" ] || procdir='proc'
-[ "$prefix" ] || prefix='dens'
-[ "$suffix" ] || suffix='dat'
-[ "$num_zeros" ] || num_zeros=7
-[ "$start" ] || start=0
+linkdir=$1
 
 # Assume the last character of the prefix is a separator before the index.
 sep=${prefix:${#prefix}-1:1}
 # Create a new directory for the symlinks if it doesn't already exist.
-if [ ! -d $symlinks ]; then
-  mkdir $symlinks
+if [ ! -d $linkdir ]; then
+  mkdir $linkdir
 fi
 # Create process directories below symlink directory
 for i in `ls -d $procdir*`
 do
-  mkdir $symlinks/$i &> /dev/null
+  mkdir $linkdir/$i &> /dev/null
 done
 # Get the current working directory
 cwd=`pwd`
 # Initialise an empty string
 string=""
 # Create a string of zeros of length specified as an argument.
-for i in `seq 0 $(( $num_zeros-1 ))`
+for i in `seq 0 $(( $numzeros-1 ))`
 do
   string="0"$string
 done
@@ -126,7 +121,7 @@ do
   # Construct the new index with the required number of zeros removed.
     new_str=${string:$zeros:${#string}}$i
     i=$(( i+1 ))
-    linkfile=$symlinks/$dir/$prefix$new_str.$suffix
+    linkfile=$linkdir/$dir/$prefix$new_str.$suffix
   # Skip this link if it already exists.
     if [ -h $linkfile ]; then
       echo $linkfile exists.  Skipping...
